stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/Dockerfile
      buildContext: .
      tag: app
      pushRemote: true
      registry: 127.0.0.1:34860
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
notification: {}
